site_name: 2 Wheeled Drive Raspberry Pi Line Follower running ROS1 Noetic
site_url: 'https://thenoobinventor.github.io/2wd-rpi-ros-line-follower/'
use_directory_urls: False
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
repo_url: https://github.com/TheNoobInventor/2wd-rpi-ros-line-follower
repo_name: TheNoobInventor/2wd-rpi-ros-line-follower
plugins:
  - search:
      lang: en
